name: Run Scraper Daily

on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 7:00 AM IST
  workflow_dispatch:      # Allow manual runs

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: pnpm install  # or use `npm install` if not using pnpm

      - name: Create .env file from secrets
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env

      - name: Run the scraper
        run: node main.js
